### ISSUE TITLE
Mailer generator

### ISSUE THREAD

**Issue by joneslee85** [lotus/lotus#347]
For DEIGirls RGSOC Team cc @inescoelho @rosafaria
bcc @jodosha 

# TODO:

* [x] Provide mailer generator
* [x] Generate mailer skeleton for new application
* [x] Provide opt-out option for app generator

# Generate mailer skeleton for new application

CLI

```
bundle exec lotus new bookshelf
```

should generate a default skeleton:

```
lib/
  bookshelf.rb # <== new Lotus::Mailer.configure block gets injected here
  bookshelf/
    mailers/
      .gitkeep
spec/
  bookshelf/
    mailers/
      .gitkeep
```

The content of `lib/bookshelf.rb` now also include:

```ruby
require 'lotus/mailer'

# Please consult Lotus::Mailer README for more details on available delivery method
Lotus::Mailer.configure do
  delivery_method do
    # development CustomDeliveryMethod, username: ..., password: ....
    # production :stmp, address: 'localhost', port: 1025
    test :test # default test env to :test delivery method
  end
end.load!
```

Please be note that this `delivery_method` DSL is not the original Lotus::Mailer version, the original version does not take in a block, this is a monkey-patched version of this DSL by Lotus gem:

```ruby
module Lotus::Mailer::Config
  module DeliveryMethod
     def delivery_method(&blk)
        # ...
     end
  end
end

# lotus/loader.rb
def _load_mailer!
  Lotus::Mailer::Configuration.class_eval do
    include Lotus::Mailer::Config::DeliveryMethod
  end
end
```

Why don't we modify the original version of lotus/mailer gem? The rule is, each individual component should not be aware of the environment notion, this env concept is only for lotusrb. So we monkey-patch the mailer class. Is it okay to monkey-patch? Well, the rule of thumb is "We only monkey-patch classes that we own", so the answer is yes.

Please ensure that you also write test for that method

# Provide opt-out option for app generator

By default `lotus-mailer` is opted-in, but users could opted-out if prefered, the flag for this is `--skip-mailer`:

```
bundle exec lotus new bookshelf --skip-mailer
```

which would not generate the default skeleton

# Provide mailer generator

CLI:

```
bundle exec lotus generate mailer signup
```

Available options for CLI:

```
--from - the sender email
--to - the sendee email
--subject - the email subject
```

that would generate:

```
lib/
  bookshelf/
    mailers/
      templates/
        signup.txt.erb
    signup.rb # Mailers::Signup
spec/
  bookshelf/
    mailers/
      signup_spec.rb
```

Then content of `lib/bookshelf/mailers/signup.rb` is:

```ruby
class Mailers::Signup
  include Lotus::Mailer

  from 'from@domain' # default value or the value set by --from flag
  to     'to@domain'  # default value or the value set by --to flag
  subject 'signup' # default value or the value set by --subject flag
end
```

The content of `spec/bookshelf/mailers/signup_spec.rb` is:

```ruby
require 'spec_helper'

describe Mailers::Signup do
  describe '.deliver' do
    # test goes here
  end
end
```

**Comment by rosafaria** [comment]
Should the specs differentiate between minitest and rspec?

**Comment by joneslee85** [comment]
@rosafaria nope, it should be the same

**Comment by jodosha** [comment]
Closed by #338
